resource_group_name    = "banking-resource-group"
location               = "East US"
storage_account_name   = "bankinguniquestorage1234"
sql_admin_user         = "radwa"
sql_admin_password     = "banking123!"
sql_server_name        = "banking-sql-server"
sql_database_name      = "bankingdb"
container_name = "bankingcontainer"
